### ISSUE TITLE
We need a better way to keep this repository in line with our frontend repository

### ISSUE THREAD

**Issue by TheYuriG** [trophy-place/community#1]
The work here is fairly manual, so the translation files in this repository will eventually get outdated as they don't get the new lines added on the frontend.

There must be a better way to address this that we need to look into. Maybe some sort of GitHub Actions that will check for files being changed on the frontend repository and then having them copies to this repository automatically?

**Comment by Makowo** [comment]
don't mind me, just testing a thing
